[[redirects]]
  from = "/biology"
  to = "https://biology-calculators-main.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/biology/sitemap.xml"
  to = "https://biology-calculators-main.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/biology*"
  to = "https://biology-calculators-main.netlify.app/biology/:splat"
  force = true
  status = 200   


[[redirects]]
  from = "/investment"
  to = "https://investment-calculators-main.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/investment/sitemap.xml"
  to = "https://investment-calculators-main.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/investment*"
  to = "https://investment-calculators-main.netlify.app/investment/:splat"
  force = true
  status = 200   


  [[redirects]]
  from = "/construction"
  to = "https://construction-calculators-main.netlify.app/"
  force = true
  status = 200

 [[redirects]]
  from = "/construction/sitemap.xml"
  to = "https://construction-calculators-main.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/construction*"
  to = "https://construction-calculators-main.netlify.app/construction/:splat"
  force = true
  status = 200   

[[redirects]]
  from = "/assets/*"
  to = "https://investment-calculators-main.netlify.app/assets/:splat"
  force = true
  status = 200  

[[redirects]]
  from = "/assets/*"
  to = "https://construction-calculators-main.netlify.app/assets/:splat"
  force = true
  status = 200



